/* ============================================================
   cheatsheets-data.js — data for cheatsheets.html (loaded first).
   window.DESIGNS = [...] — one entry per design problem.

   Schema per entry:
     icon, name, scope, tags[]        — card header
     fr[], nfr[], oos[]               — functional / non-functional / OUT OF SCOPE
     api                              — core API one-liner
     tech[[what, why], ...]           — tech choices and why
     got[]                            — deep dives / "great" moves
     arch: {                          — interactive architecture diagram
       nodes: [[id, label, kind, col, row, description], ...]
       edges: [[fromId, toId, label, description], ...]
     }
   Node kinds: cl=client, svc=service, db=datastore, q=queue/stream,
               cache=cache/in-memory, ext=external/3rd-party.
   Layout is a simple grid: col = horizontal layer, row = vertical slot.
   ============================================================ */
window.DESIGNS = [

  {icon:"🔗", name:"URL Shortener (Bitly)", scope:"shorten + redirect, read-heavy", tags:["KV","cache","counter"],
   fr:["Shorten a long URL (optional custom alias, expiry)","Redirect short code → long URL"],
   nfr:["Availability > consistency","Redirect < 100ms","~1B URLs, read:write ≈ 1000:1"],
   oos:["Click analytics dashboards","User accounts / auth","Spam & abuse detection","Custom branded domains"],
   api:"POST /urls {long,alias?,exp?} · GET /{code} → 302",
   tech:[["Any DB (Postgres/Dynamo)","write load tiny (~1/s); choice barely matters"],["Redis atomic counter + batching","unique code gen; Base62 encode; grab ~1000 ids/server"],["Redis / CDN cache","fast redirects; reads dominate"]],
   got:["302 (not 301) → keep control + analytics","UNIQUE constraint as collision safety net","Predictable ids are enumerable → don't shorten private URLs","Multi-region = disjoint counter ranges"],
   arch:{nodes:[
     ["client","Client","cl",0,1,"Browser or app. Calls the API to shorten; hits the short link to be redirected."],
     ["gw","API Gateway / LB","svc",1,1,"Routes traffic; terminates TLS; can rate-limit shortening."],
     ["write","Shorten Service","svc",2,0,"Generates the short code (Base62 of a counter value) and persists the mapping. Tiny write load — scales trivially."],
     ["read","Redirect Service","svc",2,2,"Looks up code → long URL and returns 302. This is the hot path (1000:1 reads)."],
     ["ctr","Redis Counter","cache",3,0,"Single atomic INCR source of unique ids. Each app server grabs a batch of ~1000 ids to cut round-trips."],
     ["db","Database","db",4,1,"Source of truth: code → long URL (+ owner, expiry). UNIQUE(code) is the collision safety net."],
     ["cache","Redis Cache / CDN","cache",3,2,"Caches code → URL so redirects rarely touch the DB. Read-through with TTL."]],
   edges:[
     ["client","gw","HTTPS","All traffic enters through the gateway."],
     ["gw","write","POST /urls","Shorten request: validate URL, optional custom alias / expiry."],
     ["gw","read","GET /{code}","Redirect request — the dominant traffic."],
     ["write","ctr","next id block","Atomic counter batch → collision-free ids without coordination between app servers."],
     ["write","db","INSERT code→URL","Persist mapping; UNIQUE constraint rejects a duplicate custom alias."],
     ["read","cache","lookup code","Cache hit serves the 302 in ~1ms."],
     ["cache","db","on miss","Read-through: load mapping, populate cache with TTL."]]}},

  {icon:"📦", name:"File Storage / Sync (Dropbox)", scope:"upload, sync, share large files", tags:["blob","CDN","chunking"],
   fr:["Upload / download / share files","Auto-sync across a user's devices"],
   nfr:["Availability > consistency","Files up to ~50GB","Durable, recoverable"],
   oos:["Collaborative editing (that's Google Docs)","Virus / malware scanning","Rich permission systems (start with simple share links)","Storage-quota billing"],
   api:"presigned PUT to S3 · GET via CDN signed URL · /files/changes?since=",
   tech:[["S3 (blob) + metadata DB","bytes in S3, only URL/refs in DB"],["Presigned URLs","client uploads/downloads direct to S3, bypassing app servers"],["CDN signed URLs","fast global download"]],
   got:["Chunk on the CLIENT + S3 multipart (resumable)","SHA-256 fingerprint → dedup + resume (not filename)","Content-defined chunking (rolling hash) for delta sync","Version vectors → keep both as conflicted copies (LWW silently loses edits); short-lived signed URLs"],
   arch:{nodes:[
     ["client","Client (chunker)","cl",0,1,"Splits files into chunks locally, fingerprints each (SHA-256), and syncs. Polls /changes?since= for updates from other devices."],
     ["app","File Service","svc",1,0,"Issues presigned upload/download URLs, records file & chunk metadata, answers sync queries. Never touches file bytes."],
     ["meta","Metadata DB","db",2,0,"Files, versions, chunk fingerprints, share links. Fingerprint lookup powers dedup and resumable upload."],
     ["s3","S3 Blob Store","db",2,1,"The actual bytes, chunk-per-object via multipart upload. 11-nines durability."],
     ["cdn","CDN","ext",1,2,"Edge-cached downloads via short-lived signed URLs."]],
   edges:[
     ["client","app","presign / commit / changes","Ask for presigned URLs, commit completed uploads, poll for changes since last cursor."],
     ["app","meta","file + chunk records","Metadata only — which chunks make up which version of which file."],
     ["client","s3","multipart PUT chunks","Client uploads chunks directly to S3 — app servers never proxy bytes. Failed chunks retry individually (resumable)."],
     ["client","cdn","GET signed URL","Downloads served from the edge."],
     ["cdn","s3","origin pull","CDN fetches from S3 on cache miss."]]}},

  {icon:"🎫", name:"Ticketmaster", scope:"browse + book, no double-booking", tags:["ACID","lock","search"],
   fr:["View + search events","Book tickets without double-booking"],
   nfr:["Availability for view/search; STRONG consistency for booking","10M users on one event; search < 500ms"],
   oos:["Dynamic / surge pricing","Seat-map rendering","Resale & secondary market","Fraud / bot detection"],
   api:"GET /events/:id · GET /events/search · POST /bookings/:eventId (reserve→confirm)",
   tech:[["PostgreSQL (ACID)","the real no-double-book guarantee"],["Elasticsearch","full-text search (LIKE = full scan)"],["Redis lock + TTL","seat hold ~10min, auto-release on abandon"],["Stripe tokenization + idempotent webhook","payment"]],
   got:["Lock is for UX; the ACID write is the guarantee","Virtual waiting queue for huge on-sales (staff move)","Cache + horizontal scale for hammered event pages"],
   arch:{nodes:[
     ["client","Client","cl",0,1,"Browses, searches, books. For a hot on-sale it lands in the waiting queue first."],
     ["gw","API Gateway","svc",1,1,"Routes to the three services; rate-limits; auth."],
     ["vq","Virtual Waiting Queue","q",1,2,"Admission control for huge on-sales: users enter in order, are let through at a rate booking can handle."],
     ["event","Event Service","svc",2,0,"Read path for event/venue pages. Heavily cached — one hot event gets hammered."],
     ["search","Search Service","svc",2,1,"Full-text + filters over events."],
     ["book","Booking Service","svc",2,2,"Reserve → pay → confirm flow. Holds the seat via Redis, confirms via an ACID transaction."],
     ["pg","Postgres","db",3,0,"Events, venues, seats, bookings. The transactional UPDATE ... WHERE status='available' is the real double-booking guarantee."],
     ["es","Elasticsearch","db",3,1,"Inverted index for search; kept in sync from Postgres via CDC."],
     ["lock","Redis Lock (TTL)","cache",3,2,"Seat hold for ~10 min while the user pays. TTL auto-releases abandoned carts — pure UX, not the guarantee."],
     ["stripe","Stripe","ext",4,2,"Payment. Card data is tokenized; success arrives via idempotent webhook."]],
   edges:[
     ["client","gw","HTTPS","Normal traffic goes straight in."],
     ["client","vq","hot on-sale","Taylor Swift case: 10M users are queued instead of stampeding the booking path."],
     ["vq","book","admit at safe rate","Queue releases users in order at a throughput the DB can absorb."],
     ["gw","event","view event","Event page reads — served from cache when hot."],
     ["gw","search","search events","Full-text queries; LIKE '%term%' on Postgres would full-scan."],
     ["gw","book","reserve seat","Start the reserve → confirm flow."],
     ["event","pg","events / seats","Source of truth reads (through a cache)."],
     ["search","es","query index","Tokenized full-text + filters."],
     ["pg","es","CDC sync","Change-data-capture keeps the index fresh without dual writes."],
     ["book","lock","hold seat ~10min","SET NX EX — auto-expires if the user abandons checkout."],
     ["book","pg","ACID booking txn","Transactional write; a conflicting booking fails atomically."],
     ["book","stripe","charge","Tokenized payment; webhook confirms asynchronously."]]}},

  {icon:"📰", name:"News Feed", scope:"posts, follows, reverse-chron feed", tags:["fan-out","cache","GSI"],
   fr:["Create posts; follow users","View reverse-chron feed; paginate"],
   nfr:["Availability > consistency (~1min stale ok)","< 500ms; 2B users; unlimited follows"],
   oos:["Ranking / ML feed ordering (chronological only)","Media processing pipeline (images/video)","Ads insertion","Moderation & spam"],
   api:"POST /posts · PUT /users/:id/follow · GET /feed?cursor=ts",
   tech:[["DynamoDB posts + Follow table w/ GSI","reverse lookups"],["Fan-out-on-write workers + precomputed feed","push post-id to each follower's feed; cap each feed at ~hundreds of entries. Cost scales with follower count → hybrid for celebrities"],["Feed + post cache","hot reads"]],
   got:["Hybrid fan-out: push normal users, pull celebrities, merge","Redundant cache for hot posts (Dynamo hates hot keys)","Cursor (timestamp) pagination; don't support 100-pages-deep"],
   arch:{nodes:[
     ["client","Client","cl",0,1,"Creates posts, follows users, scrolls the feed with a timestamp cursor."],
     ["gw","API Gateway","svc",1,1,"Routes writes to Post Service, reads to Feed Service."],
     ["post","Post Service","svc",2,0,"Persists the post, then emits an event so fan-out happens asynchronously — the write returns fast."],
     ["feed","Feed Service","svc",2,2,"Reads the precomputed feed, hydrates post ids into content, merges in celebrity posts (pull side of the hybrid)."],
     ["q","Fan-out Queue","q",3,0,"Buffers post-created events; absorbs bursts and decouples posting latency from fan-out cost."],
     ["posts","Posts (DynamoDB)","db",3,1,"Post content by id. Hot posts also live in a redundant cache — Dynamo hates hot keys."],
     ["fan","Fan-out Workers","svc",4,0,"For each new post: look up followers, push the post id into each follower's feed. Skipped for celebrity authors."],
     ["follows","Follows + GSI","db",4,1,"Follow edges; the GSI gives the reverse lookup (who follows X) that fan-out needs."],
     ["feeds","Feed Cache","cache",3,2,"Precomputed feed per user — a capped list (~hundreds) of post ids in reverse-chron order."]],
   edges:[
     ["client","gw","HTTPS","Both read and write traffic."],
     ["gw","post","POST /posts","Create a post."],
     ["gw","feed","GET /feed?cursor","Paginated reverse-chron read."],
     ["post","posts","write post","Persist content first, fan out after."],
     ["post","q","post-created event","Async handoff — posting stays fast regardless of follower count."],
     ["q","fan","consume","Workers scale horizontally with post volume."],
     ["fan","follows","get followers (GSI)","Reverse lookup: all followers of the author."],
     ["fan","feeds","push post id","Write into each follower's precomputed feed; capped so storage stays bounded."],
     ["feed","feeds","read precomputed ids","One cheap read instead of scatter-gather over everyone you follow."],
     ["feed","posts","hydrate + celebrity pull","Fetch content for ids; for followed celebrities, pull their recent posts at read time and merge."]]}},

  {icon:"💬", name:"WhatsApp / Chat", scope:"realtime messaging, offline delivery", tags:["WebSocket","pub/sub","inbox"],
   fr:["Group chats (≤100); send/receive","Offline delivery (~30d); media"],
   nfr:["< 500ms; guaranteed deliverability","Billions of users"],
   oos:["E2E encryption internals (Signal protocol — name it, don't design it)","Voice / video calls","Stories & status","Chat backup / export"],
   api:"WebSocket (TLS): sendMessage, newMessage, ack; L4 LB",
   tech:[["WebSocket servers + L4 LB","persistent conns; L4 suffices"],["Redis Pub/Sub (topic per user)","route to the server holding the recipient"],["Inbox table","undelivered messages, delete on ack, TTL"]],
   got:["Pub/Sub at-most-once → Inbox + acks + per-chat seq numbers (gap detect)","App-level heartbeats (TCP keepalive too slow)","NTP server-receipt timestamps for order; client sorts","Per-user channels; switch per-chat for big groups"],
   arch:{nodes:[
     ["client","Client","cl",0,1,"Holds one WebSocket; sends messages, acks deliveries, reconnects and drains its inbox after being offline."],
     ["lb","L4 Load Balancer","svc",1,1,"Layer-4 is enough — WebSocket is just a long-lived TCP connection; no per-message routing needed here."],
     ["chat","Chat Servers (WS)","svc",2,1,"Terminate WebSockets. On send: persist to recipient inboxes, publish to recipients' Pub/Sub topics. App-level heartbeats detect dead connections."],
     ["pubsub","Redis Pub/Sub","q",3,0,"Topic per user. Whichever chat server holds the recipient's connection is subscribed to that topic — this is how messages cross servers. At-most-once!"],
     ["inbox","Inbox Table","db",3,2,"Durable undelivered messages (TTL ~30d). Written BEFORE publish; deleted on client ack. This is what makes delivery guaranteed despite lossy Pub/Sub."],
     ["push","APNs / FCM","ext",4,1,"Wakes the app on a device with no live connection."]],
   edges:[
     ["client","lb","WSS","One persistent connection per device."],
     ["lb","chat","TCP passthrough","Connection pinned to one chat server for its lifetime."],
     ["chat","inbox","write, delete on ack","Persist first — if Pub/Sub drops the message, the recipient still drains it from the inbox on reconnect."],
     ["chat","pubsub","publish to user topic","Fire-and-forget fast path to whichever server holds each recipient."],
     ["pubsub","chat","deliver to holder","Subscribed server pushes the message down the recipient's WebSocket; per-chat sequence numbers let the client detect gaps."],
     ["chat","push","offline notify","No subscriber on the topic → recipient offline → send a push notification."]]}},

  {icon:"🚗", name:"Uber / Ride-sharing", scope:"location, matching, dispatch", tags:["geospatial","lock","durable-exec"],
   fr:["Fare estimate; request ride","Match nearby driver; accept/decline"],
   nfr:["Match < 1min; STRONG consistency in matching","100k requests in one location"],
   oos:["Surge-pricing algorithm","Route / ETA computation itself (use a Maps API)","Payments (assume a processor)","Pool / shared rides"],
   api:"POST /fare · POST /rides{fareId} · POST /drivers/location · PATCH /rides/:id",
   tech:[["Redis geohashing (in-memory)","~2M loc writes/s; DynamoDB too costly; B-tree can't do 2D"],["Matching svc + Redis lock TTL","no double-dispatch (~10s to accept)"],["Maps/ETA API; APNs/FCM","fares + notifications"]],
   got:["Durable execution (Temporal/Cadence) for driver-timeout flow","Adaptive client location-update intervals","Never trust client (userId/fare/ts from server/session)","Geo-sharding + read replicas to scale"],
   arch:{nodes:[
     ["rider","Rider App","cl",0,0,"Requests fare estimate, then a ride against that fareId."],
     ["driver","Driver App","cl",0,2,"Streams location every ~5s (adaptive interval); receives ride offers; accepts or declines."],
     ["gw","API Gateway","svc",1,1,"Auth + routing. Server derives userId / fare / timestamps from the session — never trusts the client."],
     ["match","Matching Service","svc",2,0,"Finds nearby drivers, offers the ride to one at a time, handles the ~10s accept window. A durable-execution workflow survives crashes mid-dispatch."],
     ["loc","Location Service","svc",2,2,"Ingests the driver location firehose (~2M writes/s at scale) — the reason a disk-based DB is out."],
     ["rides","Rides DB","db",3,0,"Ride state machine: requested → matched → in-progress → completed."],
     ["lock","Redis Lock (TTL)","cache",3,1,"Driver locked for ~10s while an offer is pending — prevents offering one driver to two riders."],
     ["geo","Redis Geo Index","cache",3,2,"GEOADD / GEOSEARCH over geohashes — in-memory 2D index; a B-tree can't answer 'nearby' efficiently."],
     ["maps","Maps / ETA API","ext",4,0,"Third-party routing for fare estimates and ETAs."],
     ["push","APNs / FCM","ext",4,1,"Delivers ride offers to drivers."]],
   edges:[
     ["rider","gw","fare, then ride request","Fare estimate first; the ride request references the quoted fareId."],
     ["driver","gw","location every ~5s","Adaptive: slower when stationary — big battery/traffic win."],
     ["gw","loc","location updates","Write-optimized hot path, separate from matching."],
     ["loc","geo","GEOADD","Update driver position in the in-memory geo index."],
     ["gw","match","ride request","Kick off matching."],
     ["match","geo","GEOSEARCH nearby","Nearest available drivers around pickup."],
     ["match","lock","lock driver ~10s","SET NX EX — no double-dispatch while an offer is pending."],
     ["match","rides","ride state","Durable state transitions; timeout → next driver (durable workflow handles this reliably)."],
     ["match","maps","fare / ETA","Delegate routing math."],
     ["match","push","offer to driver","Notification; accept/decline flows back through the gateway."]]}},

  {icon:"📊", name:"Ad Click Aggregator", scope:"near-realtime analytics over clicks", tags:["stream","Flink","OLAP","lambda"],
   fr:["Click → redirect to advertiser","Advertisers query metrics ≥1-min granularity"],
   nfr:["10k clicks/s peak; sub-second queries","No data loss; idempotent tracking"],
   oos:["Click fraud / bot detection","Ad serving & targeting (which ad to show)","Billing & invoicing pipeline","Multi-touch attribution"],
   api:"GET /click → server-side redirect",
   tech:[["Kafka/Kinesis → Flink → OLAP (ClickHouse/Druid)","stream-aggregate; not one DB for ingest+query"],["S3 data lake + nightly Spark","batch source of truth (Lambda arch) (or Kappa: reprocess from the Kafka log, skipping a separate batch layer)"]],
   got:["Hot ad → random suffix on partition key (aggregator SUMs)","Reconcile stream (speed) vs batch (truth)","Unique impression id for dedup","Pre-aggregate rollups for fast queries"],
   arch:{nodes:[
     ["user","User","cl",0,0,"Clicks an ad; gets a server-side redirect to the advertiser (so the click is always captured)."],
     ["click","Click Service","svc",1,0,"Stateless: log the click event with its impression id, 302 to the target. Scales horizontally."],
     ["kafka","Kafka","q",2,0,"Durable click log, partitioned by AdId (hot ads get a random suffix). Replayable — the recovery and reprocessing story."],
     ["flink","Flink Aggregator","svc",3,0,"Tumbling 1-min windows per ad; checkpointed state; flushes aggregates. Speed layer."],
     ["olap","OLAP (ClickHouse)","db",4,0,"Columnar store for slice-and-dice queries over minute-level aggregates in sub-second."],
     ["s3","S3 Data Lake","db",3,1,"Raw events dumped from Kafka via a connector — cheap, immutable source of truth."],
     ["spark","Spark (nightly)","svc",4,1,"Recomputes exact daily aggregates from raw events; overwrites the stream's numbers. Batch layer of the lambda architecture."],
     ["adv","Advertiser","cl",0,2,"Queries dashboards: clicks by ad / minute / region."],
     ["query","Query Service","svc",2,2,"Serves advertiser queries from the OLAP store; caches common rollups."]],
   edges:[
     ["user","click","GET /click","Server-side redirect beats a client-side pixel — no lost tracking."],
     ["click","kafka","click event","Append with unique impression id for downstream dedup."],
     ["kafka","flink","consume","Exactly-once via checkpoints + idempotent sink."],
     ["flink","olap","minute aggregates","Pre-aggregated rollups keep queries fast."],
     ["kafka","s3","raw dump (connector)","Every event lands in the lake untouched."],
     ["s3","spark","nightly batch","Recompute from raw = the truth."],
     ["spark","olap","reconciled truth","Batch overwrites stream results — catches any streaming drift or loss."],
     ["adv","query","dashboard queries","Sliceable metrics, ≥1-min granularity."],
     ["query","olap","sub-second slices","Columnar scans over pre-aggregated data."]]}},

  {icon:"🕷️", name:"Web Crawler", scope:"crawl + extract text at scale", tags:["SQS","S3","politeness"],
   fr:["Crawl from seed URLs","Extract + store page text"],
   nfr:["Fault tolerant (resume); polite (robots.txt)","10B pages < 5 days"],
   oos:["Search indexing & ranking (crawl + extract only)","JS rendering (headless browsers)","Near-duplicate detection beyond content hash","Freshness / recrawl scheduling policy"],
   api:"frontier queue → fetch → S3 → extract",
   tech:[["SQS frontier","visibility timeout → backoff + DLQ; store URL ptr, not HTML"],["Fetch/extract workers + S3","raw HTML / text"],["Metadata DB + DNS cache","dedup; DNS is a bottleneck"]],
   got:["~1 req/s per domain (Redis SET NX) + jitter; respect Crawl-delay","DNS ~70% of thread time → cache + multiple providers","Content-hash dedup (not just URL); max depth ~15–20"],
   arch:{nodes:[
     ["frontier","Frontier (SQS)","q",0,1,"URLs to crawl. Visibility timeout = built-in retry: a crashed worker's URL reappears automatically. DLQ catches permanent failures."],
     ["fetch","Fetcher Workers","svc",1,1,"Pull URL → check politeness → resolve DNS → GET → store raw HTML → enqueue a parse job. IO-bound, thousands of async requests per box."],
     ["polite","Politeness (Redis)","cache",1,0,"~1 req/s per domain via SET NX + jitter; honors robots.txt and Crawl-delay. Not optional — you'll get IP-banned."],
     ["dns","DNS Cache","cache",2,0,"DNS is ~70% of naive thread time. Cache aggressively + spread across providers."],
     ["s3raw","S3 Raw HTML","db",2,1,"Immutable raw pages. Queues carry a pointer to S3, never the HTML itself."],
     ["pq","Parse Queue","q",2,2,"Decouples fetching from parsing so each side scales and fails independently."],
     ["parser","Parser Workers","svc",3,2,"Extract text + links from raw HTML. CPU-bound (vs IO-bound fetchers) — separate fleet, separate scaling."],
     ["meta","Metadata DB","db",3,1,"Seen URLs and content hashes. Hash dedup catches the same page under different URLs; max depth ~15–20 stops loops."],
     ["s3txt","S3 Extracted Text","db",4,2,"Final output for downstream consumers."]],
   edges:[
     ["frontier","fetch","URL (visibility timeout)","Not-deleted-until-done semantics gives at-least-once fetching."],
     ["fetch","polite","rate check per domain","Skip and requeue if the domain's slot is taken."],
     ["fetch","dns","resolve (cached)","Cache hit avoids the crawl's biggest hidden bottleneck."],
     ["fetch","s3raw","store raw HTML","Blob to S3; pointer travels onward."],
     ["fetch","pq","parse job (S3 ptr)","Hand off to the CPU-bound side."],
     ["pq","parser","consume","Parser fleet scales on queue depth."],
     ["parser","s3txt","extracted text","The deliverable."],
     ["parser","meta","hash + URL dedup","Drop already-seen content before it re-enters the frontier."],
     ["parser","frontier","discovered URLs","New links (depth+1) feed the loop."]]}},

  {icon:"🔥", name:"Top-K (YouTube)", scope:"top-K most-viewed in a window", tags:["stream","CMS","shard+merge"],
   fr:["Ingest VideoID view stream","Query top-K (hour/day/month/all)"],
   nfr:["Tumbling windows; K ~1k","Precise unless explicitly relaxed"],
   oos:["Personalized / per-user top-K","Sliding (vs tumbling) windows","Per-region breakdowns (same design × N)","Trending detection (velocity, ML)"],
   api:"ingest views → query top-K per window",
   tech:[["Kafka ingest + sharded counters","700k TPS exceeds one DB"],["OLAP / cache for top-K","precompute per window (cron)"]],
   got:["Shard counts + merge per-shard top-K = exact","Count-Min Sketch when approximate is allowed","Tumbling (not sliding) keeps aggregation tractable"],
   arch:{nodes:[
     ["src","View Events","cl",0,1,"The firehose: every video view emits an event. ~700k TPS — beyond any single counter."],
     ["kafka","Kafka","q",1,1,"Partitioned by VideoID so all counts for one video land on the same consumer — makes per-shard counting exact."],
     ["cnt","Sharded Counters","svc",2,1,"Each shard counts its subset of videos for the current tumbling window and maintains a local top-K heap."],
     ["heap","Per-shard Top-K","cache",3,1,"A K-sized min-heap per shard — tiny memory, O(log K) updates."],
     ["merge","Merger (per window)","svc",3,0,"At window close, merges N per-shard top-K lists. Because sharding is BY VIDEO, the merged list is exact — the classic correctness argument."],
     ["snap","Top-K Snapshots","db",4,0,"Materialized top-K per window (hour/day/month); month = merge of dailies."],
     ["query","Query API","svc",4,1,"Reads a precomputed snapshot — O(1), no aggregation at query time."]],
   edges:[
     ["src","kafka","VideoID views","Durable, replayable ingest."],
     ["kafka","cnt","partition by VideoID","Same video → same shard, always."],
     ["cnt","heap","increment + heapify","Count and maintain the running top-K in one pass."],
     ["heap","merge","per-shard top-K","N small lists, not N full count tables."],
     ["merge","snap","exact merged top-K","Write once per window close."],
     ["query","snap","read window","Query = key lookup; use Count-Min Sketch instead of exact counters only if approximate is explicitly allowed."]]}},

  {icon:"🚦", name:"Distributed Rate Limiter", scope:"limit requests per client", tags:["token-bucket","Redis","gateway"],
   fr:["Limit requests per user/IP/API-key","Return 429 when over limit"],
   nfr:["< 10ms overhead; eventual consistency ok","1M req/s"],
   oos:["Monthly quotas & billing","L3/L4 DDoS protection (that's the CDN / scrubbing layer)","Self-serve rule-management UI","Per-request cost-based limiting"],
   api:"isAllowed(clientId,rule) → {pass, remaining, reset}",
   tech:[["Token bucket","allows bursts up to bucket size"],["Centralized Redis (sharded by client)","per-instance counters fail (LB spreads traffic)"]],
   got:["Atomic check/refill via MULTI or Lua; EXPIRE avoids leak","Fail-closed for social (failures coincide with spikes)","Fixed-window has 2× burst at the boundary"],
   arch:{nodes:[
     ["client","Client","cl",0,1,"Any caller identified by user id, API key, or IP."],
     ["gw","Gateway + Limiter","svc",1,1,"Middleware in front of everything: computes the bucket key, asks Redis atomically, passes or returns 429 with Retry-After."],
     ["redis","Redis Cluster","cache",2,0,"Token-bucket state, sharded by client key so one client's counter lives on one node. Lua script = atomic check-and-refill; EXPIRE stops key leaks."],
     ["rules","Rules Config","db",2,2,"Limits per key class (tier, endpoint). Cached in the gateway; eventual consistency of rule changes is fine."],
     ["backend","Backend Services","svc",3,1,"Protected services — only see requests that passed."]],
   edges:[
     ["client","gw","request","Every request pays the limiter tax — keep it < 10ms."],
     ["gw","redis","Lua: check + refill","One atomic round-trip: refill tokens by elapsed time, consume one, return remaining. No read-modify-write race."],
     ["gw","rules","limits (cached)","Rules pulled and cached locally; no per-request DB hit."],
     ["gw","backend","pass","Under limit → forward. Over → 429 (fail-closed if Redis is down: failures correlate with attack spikes)."]]}},

  {icon:"📝", name:"Google Docs", scope:"realtime collaborative editing", tags:["WebSocket","OT","Cassandra","ZooKeeper"],
   fr:["Concurrent multi-user edit; realtime view","Cursors / presence"],
   nfr:["Eventually consistent; < 100ms","≤ 100 concurrent editors/doc (extras read-only)"],
   oos:["Offline editing + merge-on-reconnect","Comments & suggestion mode","Permissions / sharing model","Rich media embedding"],
   api:"WebSocket: send edits as operations (insert/delete @pos)",
   tech:[["WebSocket doc servers","persistent edit channel"],["Operational Transformation (OT)","converge concurrent edits (CRDT = P2P/larger)"],["Cassandra ops store; ZooKeeper hash ring","append-only ops; route editors of a doc to one server"]],
   got:["Send ops, not the whole doc","Consistent hashing by documentId","Snapshot/compact operations to bound storage/join cost"],
   arch:{nodes:[
     ["client","Editor Client","cl",0,1,"Sends edits as operations (insert/delete @ position), applies transformed ops from others, renders cursors."],
     ["gw","Doc Router","svc",1,1,"Looks up which doc server owns this documentId and routes the WebSocket there."],
     ["zk","ZooKeeper","ext",1,0,"Holds the consistent-hash ring documentId → server, so ALL editors of a doc land on ONE server — that's what makes OT ordering tractable."],
     ["ws","Doc Server (WS + OT)","svc",2,1,"Owns its documents: receives ops, transforms them against concurrent ops (OT), assigns order, broadcasts to all connected editors."],
     ["cass","Ops Log (Cassandra)","db",3,0,"Append-only operation history per doc — write-heavy friendly; replay rebuilds any doc state."],
     ["snap","Snapshots (S3)","db",3,2,"Periodic compaction: snapshot + recent ops bounds join time and storage; old ops can be truncated."]],
   edges:[
     ["client","gw","open doc","Initial connect; reconnects re-route the same way."],
     ["gw","zk","docId → server","Ring lookup; ring rebalances when servers join/leave."],
     ["gw","ws","route to owner","Single-server-per-doc = a total order of ops without distributed consensus per keystroke."],
     ["ws","client","broadcast transformed ops","Everyone converges to the same doc; ops are tiny vs re-sending the document."],
     ["ws","cass","append ops","Durability; the ops log is the source of truth."],
     ["ws","snap","periodic snapshot","New editor loads snapshot + tail of ops instead of replaying years of history."]]}},

  {icon:"💳", name:"Payment System (Stripe)", scope:"charge cards, durable + auditable", tags:["idempotency","event-sourcing","PCI"],
   fr:["Merchant initiates charge; user pays by card","Merchant views status (pending/success/failed)"],
   nfr:["Highly secure; durable/auditable (never lose data)","Transaction-safe over async networks; 10k+ TPS"],
   oos:["Payouts / settlement to merchants","FX & multi-currency","Fraud scoring (Radar-style ML)","Subscriptions & invoicing"],
   api:"POST /payment-intents · POST /…/transactions · GET /…/:id",
   tech:[["API gateway (API keys + request signing)","secure entry"],["Payment-intent svc + DB; transaction svc → networks","HSMs, ISO 8583, PCI"],["Kafka event log (event sourcing)","append-only audit trail"]],
   got:["Idempotency keys + reconciliation (timeout ≠ failure)","Event sourcing for audit / chargebacks","Tokenize card data (raw PAN never hits backend)","Webhooks: idempotent, exactly-once"],
   arch:{nodes:[
     ["merchant","Merchant","cl",0,0,"Creates a payment intent with an idempotency key; receives status via signed webhooks."],
     ["payer","Payer (card form)","cl",0,2,"Enters card details into a hosted form that talks straight to the vault — the merchant (and most of our backend) never sees the PAN."],
     ["gw","API Gateway","svc",1,1,"API-key auth + request signing; the secure front door."],
     ["intent","Payment Intent Svc","svc",2,0,"Owns the intent state machine (created → processing → succeeded/failed). Idempotency key dedupes retried creates."],
     ["vault","Tokenization Vault","svc",2,2,"PCI-scoped enclave with HSMs: card → token. Shrinks the compliance boundary to one service."],
     ["db","Intents DB","db",3,0,"Current state per intent; rebuilt-able from the event log."],
     ["txn","Transaction Svc","svc",3,2,"Executes the charge against card networks using the token. Timeout ≠ failure — reconciliation resolves unknowns."],
     ["events","Kafka Event Log","q",3,1,"Append-only, event-sourced trail of every state change — the audit story for disputes and chargebacks."],
     ["network","Card Networks","ext",4,2,"Acquirer → Visa/MC via ISO 8583. Slow, async, occasionally ambiguous."],
     ["webhook","Webhook Svc","svc",4,0,"Pushes status to merchants: signed, retried, idempotent (merchants may see duplicates — design for it)."]],
   edges:[
     ["merchant","gw","create intent (idem key)","Retrying the same key returns the same intent — no double charge."],
     ["payer","vault","card → token","Raw card data only ever touches the vault."],
     ["gw","intent","route","Authenticated, signed requests only."],
     ["intent","db","state machine","Every transition persisted before acknowledged."],
     ["intent","txn","execute charge","With the token, never the PAN."],
     ["txn","network","ISO 8583 auth","If it times out, the charge state is UNKNOWN until reconciliation with the network's records."],
     ["txn","events","append events","Immutable history of attempts and outcomes."],
     ["events","webhook","status events","Event log drives notifications — nothing is lost if the webhook service crashes."],
     ["webhook","merchant","signed webhook","At-least-once delivery; merchant dedupes by event id."]]}},

  {icon:"📺", name:"YouTube / Video Streaming", scope:"upload, transcode, stream at scale", tags:["blob","CDN","DAG","read-heavy"],
   fr:["Upload videos (huge files)","Watch: adaptive-bitrate streaming","Video metadata (title, description)"],
   nfr:["Availability > consistency","Files up to ~256GB; upload resumable","Low startup latency, no buffering; read:write ≫ 100:1"],
   oos:["Recommendations & search ranking","Comments / likes / subscriptions","Copyright detection (ContentID)","Live streaming","Monetization / ads"],
   api:"POST /videos → presigned multipart · GET /videos/:id → manifest URL · segments via CDN",
   tech:[["S3 + presigned multipart upload","huge files go client → S3 directly, resumable per-chunk"],["Transcoding pipeline as a DAG (split → per-format transcode → audio → manifests)","orchestrated via queue/Temporal; parallel by segment turns hours into minutes"],["Cassandra/Dynamo video metadata","video → formats → segment refs; read-heavy, key-value shaped"],["HLS/DASH manifests + CDN","client picks per-segment quality = adaptive bitrate"]],
   got:["Segment-level parallel transcoding (the DAG) is THE deep dive","Adaptive bitrate = client-side decision from the manifest, not server logic","Fingerprint chunks for resumable upload (Dropbox trick reused)","Never proxy video bytes through app servers"],
   arch:{nodes:[
     ["client","Client","cl",0,1,"Uploads via presigned multipart; plays by fetching a manifest, then pulling segments at whatever quality the current bandwidth supports."],
     ["gw","API Gateway","svc",1,1,"Metadata CRUD + issuing presigned upload URLs."],
     ["meta","Video Metadata DB","db",2,0,"Video record → available formats → segment URLs. Key-value access pattern at huge read volume — Cassandra/Dynamo territory."],
     ["s3","S3 (raw + processed)","db",2,2,"Raw uploads land here; transcoded segments and manifests are written back here. All bytes live in blob storage."],
     ["orch","Transcode Orchestrator","q",3,1,"S3 upload event kicks off a DAG (Temporal/Step Functions): split into segments → transcode each segment × each format in parallel → audio → stitch manifests."],
     ["work","Transcode Workers","svc",4,1,"Elastic fleet of ffmpeg boxes; each takes one (segment, format) task — parallelism turns a 2-hour job into minutes."],
     ["cdn","CDN","ext",1,2,"Serves manifests and segments from the edge — startup latency and buffering live or die here."]],
   edges:[
     ["client","gw","POST /videos","Create record, get presigned multipart URLs."],
     ["client","s3","multipart PUT","Direct upload, resumable chunk-by-chunk; app servers never see bytes."],
     ["s3","orch","upload-complete event","Event-driven kickoff of the processing DAG."],
     ["orch","work","(segment, format) tasks","Fan out; retries per task; the DAG tracks completion."],
     ["work","s3","segments + manifests","Processed renditions written back next to the raw file."],
     ["orch","meta","mark ready + refs","Video becomes watchable when manifests exist."],
     ["gw","meta","GET /videos/:id","Returns metadata + manifest URL."],
     ["client","cdn","manifest + segments","Player requests segment N at quality Q; switches Q per segment as bandwidth changes — that IS adaptive bitrate."],
     ["cdn","s3","origin pull","Edge miss falls back to blob storage."]]}},

  {icon:"📍", name:"Yelp / Proximity Search", scope:"find businesses near me, with filters", tags:["geo","read-heavy","denormalize"],
   fr:["Search businesses by location + category + rating","View business with reviews","Leave a review (one per user per business)"],
   nfr:["Read-heavy (search ≫ write); search < 500ms","Eventual consistency fine (new review may lag)","10M businesses, 100M users"],
   oos:["Table reservations / bookings","Ads & promoted results","Photo storage pipeline","Fake-review / fraud detection"],
   api:"GET /search?lat&lng&radius&category&minRating · GET /businesses/:id · POST /businesses/:id/reviews",
   tech:[["Elasticsearch geo_point (or Postgres+PostGIS)","geo + category + rating filters must live in ONE index — intersecting two systems' results is the classic fail"],["CDC from business DB → ES","one writable source of truth, search index follows"],["Denormalized avg_rating on the business record","incrementally updated (count,sum) — never recompute from all reviews"],["UNIQUE(user_id, business_id)","one-review rule enforced by the DB, not app code"]],
   got:["Geohash prefix vs quadtree discussion — geohash-in-index wins for simplicity","Filter + geo in the same index — say this explicitly","Rating update: new_avg from (sum+x, n+1) atomically","Hot areas (Manhattan) → cache search results by geohash cell + filters"],
   arch:{nodes:[
     ["client","Client","cl",0,1,"Searches nearby with filters; reads business pages; posts reviews."],
     ["gw","API Gateway","svc",1,1,"Splits read (search/view) and write (review) paths."],
     ["search","Search Service","svc",2,0,"Builds the ES query: geo_distance filter + category + min rating, sorted by distance/rating."],
     ["es","Elasticsearch","db",3,0,"geo_point index with all filterable fields denormalized in — one query answers the whole search."],
     ["biz","Business/Review Svc","svc",2,2,"Business pages and review writes; updates the denormalized rating in the same transaction."],
     ["db","Business DB (Postgres)","db",3,2,"Businesses, reviews, avg_rating (count+sum). UNIQUE(user_id,business_id) enforces one review per user."],
     ["cache","Geo-cell Cache","cache",3,1,"Results cached by (geohash cell, filters) — hot cities are extremely cacheable."]],
   edges:[
     ["client","gw","HTTPS","Search is the dominant traffic."],
     ["gw","search","GET /search","Lat/lng + radius + filters."],
     ["search","cache","cell + filter key","Hot Manhattan queries mostly never reach ES."],
     ["search","es","geo + filter query","Single-index query — no cross-system intersection."],
     ["gw","biz","view / review","Business page reads and review writes."],
     ["biz","db","txn: review + rating","Insert review AND update (sum,count) atomically; unique constraint rejects a second review."],
     ["db","es","CDC sync","Index follows the source of truth; seconds of lag is acceptable."]]}},

  {icon:"❤️", name:"Tinder", scope:"nearby profile deck, swipes, matches", tags:["geo","cache","write-heavy","Bloom"],
   fr:["Deck of nearby profiles matching preferences","Swipe right/left","Match when both swipe right (notify)"],
   nfr:["~20M DAU, ~100 swipes/day each (write-heavy)","Deck feels instant → precompute","Never miss a mutual match (consistency where it counts)"],
   oos:["Post-match chat (that's the WhatsApp design)","ML profile ranking / ELO","Premium features & payments","Trust & safety / verification"],
   api:"GET /feed?lat&lng · POST /swipes {targetId, dir} · match push",
   tech:[["ES / geo index for candidate generation","distance + age/prefs filters"],["Precomputed deck in Redis (async)","feed feels instant; refresh in background"],["Cassandra for swipes, partition by swiping user","huge write volume, append-only shape"],["Atomic mutual-check (Redis Lua or single-partition read)","the simultaneous right-swipe race"]],
   got:["Exclude already-swiped: Bloom filter or swipe cache per user (false positives just skip a profile — acceptable!)","Simultaneous mutual swipe → both check-then-create can miss the match: make check+create atomic","Deck staleness vs precompute cost trade-off","Hot metros → shard geo index by region"],
   arch:{nodes:[
     ["client","Client","cl",0,1,"Pulls a precomputed deck; sends swipes; receives match notifications."],
     ["gw","API Gateway","svc",1,1,"Routes feed reads and swipe writes."],
     ["feed","Feed Service","svc",2,0,"Serves the deck from cache; triggers background regeneration when it runs low."],
     ["geo","Geo Index (ES)","db",3,0,"Candidate generation: nearby + preference filters."],
     ["deck","Deck Cache (Redis)","cache",4,0,"Precomputed profile queue per user, already filtered by the Bloom filter of past swipes."],
     ["swipe","Swipe Service","svc",2,2,"Records the swipe; on right-swipe atomically checks whether the reverse swipe exists → creates a match."],
     ["swdb","Swipes (Cassandra)","db",3,2,"Partition by swiper → each user's history on one partition; absorbs ~2B swipes/day append-only."],
     ["push","APNs / FCM","ext",4,1,"\"It's a match\" to both users."]],
   edges:[
     ["client","gw","HTTPS","Feed pulls + swipe stream."],
     ["gw","feed","GET /feed","Instant deck from cache."],
     ["feed","geo","candidate query","Nearby profiles matching age/prefs; runs async to refill the deck."],
     ["feed","deck","read + refill","Serve from Redis; regenerate in the background before it empties."],
     ["gw","swipe","POST /swipes","The write-heavy path."],
     ["swipe","swdb","append + mutual check","Append the swipe (also feeds the per-user Bloom filter). On right-swipe: does target→me exist? Check + match-create must be atomic (Lua / single partition + LWT), or two simultaneous right-swipes can both see 'no match'."],
     ["swipe","push","match notification","Both parties notified on mutual right-swipe."]]}},

  {icon:"🔎", name:"FB Post Search", scope:"keyword search over posts — build the index yourself", tags:["inverted-index","write-heavy","shard"],
   fr:["Search posts by keyword","Sort by recency or by like count"],
   nfr:["Write-heavy: ~10k posts/s ingested, likes 100k/s","Search < 500ms; post searchable < 1 min","No Elasticsearch allowed — build the inverted index"],
   oos:["Personalized / ML relevance ranking","Typo tolerance, synonyms, stemming","Privacy / ACL filtering (flag it, then scope out)","Media (image/video) search"],
   api:"GET /search?q&sort=time|likes&cursor",
   tech:[["Kafka → indexer workers","decouple post/like ingest from index writes"],["Inverted index in sharded Redis/RocksDB: term → posting list","shard BY TERM; two lists per term: by-time and by-likes (capped)"],["Like events update the by-likes list asynchronously","tolerate slightly stale like-ordering"],["Query service: fan out to term shards, intersect/merge","AND queries intersect posting lists"]],
   got:["Two sorted posting lists per term (creation-time, like-count) is the key insight","Cap hot posting lists (~1–10k entries) + cold full copy in blob storage","Popular queries → cache full result pages (even in CDN)","Shard by term (few lookups, hot-term skew) vs by doc (every query hits all shards) — know the trade-off"],
   arch:{nodes:[
     ["poster","Post/Like Events","cl",0,0,"Every new post and every like lands here as an event — search is a downstream consumer of the write firehose."],
     ["kafka","Kafka","q",1,0,"Buffers ingestion; index rebuild = replay the log."],
     ["idx","Indexer Workers","svc",2,0,"Tokenize post → for each term, append post id to that term's by-time list; like events re-rank the by-likes list."],
     ["shards","Index Shards (term → lists)","db",3,0,"Sharded by term. Each term holds two posting lists: sorted by time, sorted by likes (capped; overflow to blob storage)."],
     ["searcher","Client","cl",0,2,"Issues keyword queries with a sort order."],
     ["query","Query Service","svc",2,2,"Tokenizes the query, fetches posting lists from the right shards, intersects (AND), paginates by cursor."],
     ["cache","Query Cache","cache",3,2,"Full cached result pages for popular queries — a huge fraction of real search traffic."]],
   edges:[
     ["poster","kafka","posts + likes","Two event types, one durable log."],
     ["kafka","idx","consume","Indexing lag budget: < 1 min from post to searchable."],
     ["idx","shards","append / re-rank","By-time list is an append; by-likes is a scored update."],
     ["searcher","query","GET /search","Keyword + sort + cursor."],
     ["query","cache","popular queries","Cache hit skips the shards entirely."],
     ["query","shards","fetch posting lists","One shard per query term (that's why term-sharding needs few lookups); merge/intersect in the service."]]}},

  {icon:"🏃", name:"Strava", scope:"record activities offline, share, leaderboards", tags:["offline-first","ZSET","batch-upload"],
   fr:["Record run/ride (GPS trail) — including with NO connectivity","View own + friends' activities","Segment/challenge leaderboards"],
   nfr:["Offline-first: recording never depends on network","Read own activity immediately after save","Eventual consistency for friends/leaderboards; battery-friendly"],
   oos:["Route planning & map rendering","Segment-matching algorithm details (flag as ML/geo matching)","Social graph management","Live location sharing (Beacon)"],
   api:"POST /activities (batched points, idempotent id) · GET /feed · GET /segments/:id/leaderboard",
   tech:[["On-device buffer (SQLite) + batched upload","the client IS a database; upload when connected, client-generated activity id = idempotent retry"],["Activities DB + points as compressed blob (S3)","GPS trails are big and read whole — blob, not rows"],["Redis sorted sets per segment (+ per-week keys)","leaderboard = ZADD GT / ZREVRANGE; time-bucketed keys with TTL"],["Simple fan-out feed","follower counts are small — plain fan-out-on-write works"]],
   got:["Offline-first is the differentiating requirement — say 'the phone is the primary datastore while recording'","Idempotent upload (client UUID) — flaky networks WILL retry","Simplify GPS trail (Douglas-Peucker) before storing/rendering","Redis holds top-N only; full standings in DB — memory math matters"],
   arch:{nodes:[
     ["phone","Phone (offline buffer)","cl",0,1,"Records GPS points into local SQLite regardless of connectivity; uploads in batches with a client-generated activity UUID when a connection appears."],
     ["gw","API Gateway","svc",1,1,"Auth + routing; dedupes retried uploads by activity UUID."],
     ["act","Activity Service","svc",2,1,"Validates, simplifies the trail (Douglas-Peucker), stores metadata + blob, then emits events for feed and leaderboards."],
     ["adb","Activities DB","db",3,0,"Activity metadata: user, distance, time, segment efforts. Read-your-own-write for the athlete who just finished."],
     ["s3","GPS Trails (S3)","db",3,1,"Compressed point arrays as blobs — always read whole, never queried row-by-row."],
     ["lb","Leaderboards (Redis ZSET)","cache",3,2,"One sorted set per (segment, time window): ZADD GT keeps the best effort; weekly keys expire via TTL."],
     ["feed","Feed Service","svc",4,0,"Fan-out-on-write to followers — graphs are small here, no celebrity problem."]],
   edges:[
     ["phone","gw","batched upload (UUID)","Same UUID on retry → server upserts instead of duplicating the run."],
     ["gw","act","POST /activities","The only write path."],
     ["act","adb","activity record","Metadata queryable for feeds/stats."],
     ["act","s3","compressed trail","Blob of points; DB row holds the pointer."],
     ["act","lb","ZADD GT best effort","Only improves your score; per-window keys make daily/weekly boards free."],
     ["act","feed","fan-out event","Push activity id into followers' feeds."],
     ["feed","adb","hydrate activities","Feed read: ids → activity cards."]]}},

  {icon:"⚖️", name:"LeetCode / Online Judge", scope:"run untrusted code safely, contest scale", tags:["containers","queue","isolation","ZSET"],
   fr:["Browse problems; submit code","Run against test cases → verdict","Live contest leaderboard"],
   nfr:["Isolation: users submit HOSTILE code","Verdict within ~5s (but async, not blocking)","Contest spike: 100k concurrent submitters"],
   oos:["Plagiarism / cheating detection","Problem authoring & editorial content","Payments / premium","In-browser IDE features (autocomplete, LSP)"],
   api:"POST /problems/:id/submissions · GET /submissions/:id (poll/SSE) · GET /contests/:id/leaderboard",
   tech:[["SQS between API and judges","absorbs the contest thundering herd; API returns submission id immediately"],["Container sandbox per run (gVisor/Firecracker)","no network, read-only FS, CPU/mem/time/pid limits, output caps"],["Prewarmed container pool","cold starts would eat the entire 5s budget"],["Redis ZSET leaderboard, cached with ~5s TTL","contest ranking without hammering the DB"]],
   got:["NEVER exec in the API process — the queue+sandbox split is the whole design","Enumerate the attack surface out loud: fork bombs (pid limit), infinite loops (wall-clock kill), exfiltration (no egress), giant output (cap)","Per-language time multipliers for fair limits","Poll vs SSE for verdict delivery — either is fine, justify"],
   arch:{nodes:[
     ["client","Client","cl",0,1,"Submits code; polls (or SSE-subscribes) for the verdict; watches the contest leaderboard."],
     ["api","API Service","svc",1,1,"Accepts the submission, enqueues it, returns the submission id instantly — never runs code itself."],
     ["q","Submission Queue (SQS)","q",2,0,"The shock absorber: a contest's 100k simultaneous submissions drain at the judges' pace; visibility timeout retries crashed runs."],
     ["judge","Judge Workers","svc",3,0,"Pull a job, run it in a fresh sandbox from the prewarmed pool against the test cases, record the verdict."],
     ["box","Sandbox Pool","svc",4,0,"gVisor/Firecracker containers: no network, read-only FS, cpu/mem/pid/time limits, output size caps. One run per container, then destroyed."],
     ["db","Submissions DB","db",3,1,"Code, status, verdict, runtime — what the client polls."],
     ["lb","Leaderboard (Redis)","cache",3,2,"ZSET by (solved, penalty time); serving copy cached ~5s — thousands of viewers, one recompute."]],
   edges:[
     ["client","api","POST submission","Async contract: 202 + submission id."],
     ["api","q","enqueue","Spike-proof handoff."],
     ["q","judge","pull job","Judges scale on queue depth; slow drain is acceptable, dropped work is not."],
     ["judge","box","run in sandbox","The isolation boundary — treat every submission as an attack."],
     ["judge","db","verdict","Accepted / WA / TLE / MLE / RE + runtime."],
     ["judge","lb","score update","Contest submissions also bump the ZSET."],
     ["client","db","poll verdict","Via the API; or push it over SSE."],
     ["client","lb","GET leaderboard","Cached ranking, ~5s staleness is invisible."]]}},

  {icon:"⏰", name:"Distributed Job Scheduler", scope:"run jobs at time T / on cron, reliably", tags:["cron","two-layer","at-least-once"],
   fr:["Schedule one-off (at time T) and recurring (cron) jobs","Execute with retries; report status/history"],
   nfr:["At-least-once execution — a due job is NEVER missed","Precision: start within ~2s of scheduled time","10k+ executions/s; durable across crashes"],
   oos:["Workflow DAGs / dependencies (that's Airflow/Temporal)","Deploying/versioning the job CODE","Multi-tenant quotas & billing","Exactly-once side effects (push idempotency to handlers)"],
   api:"POST /jobs {at|cron, payload} · GET /jobs/:id/runs",
   tech:[["Jobs table + derived Executions table partitioned by time bucket","cron rows materialize only their NEXT run; executions are the pollable work"],["Poller: query next ~5-min window → push to SQS with per-message delay","coarse DB scan + fine queue-delay = 2s precision without hammering the DB"],["SQS + workers","visibility timeout gives retry-on-crash for free; DLQ for poison jobs"],["Idempotency key = (job id, scheduled time)","retries can't double-run a logical execution"]],
   got:["The two-layer trick (coarse DB window + fine delay queue) IS the design — lead with it","After executing a cron job, compute and insert the next execution","Leader election (or partitioned pollers) so exactly one poller owns a window","Don't keep the whole schedule in Redis ZSET only — durability first"],
   arch:{nodes:[
     ["client","Client / Services","cl",0,1,"Creates jobs: 'run at T' or a cron expression, with a payload describing what to invoke."],
     ["api","Scheduler API","svc",1,1,"CRUD on jobs; materializes the first execution row."],
     ["jdb","Jobs + Executions DB","db",2,1,"Jobs (definition) and Executions (due instances) partitioned by time bucket — the durable schedule."],
     ["poll","Poller (leader)","svc",2,0,"Every ~5 min, one elected poller reads the next window of due executions and enqueues them with fine-grained delays."],
     ["q","Delay Queue (SQS)","q",3,0,"Per-message delay lands each job within seconds of its due time; visibility timeout = automatic retry if a worker dies mid-run."],
     ["work","Workers","svc",4,0,"Execute the payload idempotently (key = job id + scheduled time); report status; failures retry with backoff, then DLQ."],
     ["dlq","DLQ","q",4,1,"Poison executions land here for inspection instead of retrying forever."]],
   edges:[
     ["client","api","create job","One-off or cron."],
     ["api","jdb","job + next execution","Cron expands lazily: only the next occurrence exists as a row."],
     ["poll","jdb","query due window","SELECT executions WHERE due < now+5min — cheap, coarse, index-friendly."],
     ["poll","q","enqueue w/ delay","Fine timing moves from the DB to the queue."],
     ["q","work","deliver at due time","At-least-once: not deleted until the worker confirms."],
     ["work","jdb","status + next cron run","Record outcome; insert the following execution for recurring jobs."],
     ["work","dlq","after N failures","Keep the pipeline moving past poison jobs."]]}},

  {icon:"🔔", name:"Notification Service", scope:"multi-channel notify at fan-out scale", tags:["fan-out","Kafka","idempotency","providers"],
   fr:["Send to a user via push / email / SMS per their prefs","Broadcast to millions (announcement)","Respect opt-outs; dedup/collapse"],
   nfr:["At-least-once + dedup ≈ user sees it once","Broadcast fan-out without melting the API","Per-provider rate limits respected; seconds-level latency"],
   oos:["Template authoring / campaign UI","Audience segmentation & targeting ML","Open/click analytics pipeline","In-app inbox (separate feed system)"],
   api:"POST /notify {userId|segment, event, channels?} · PUT /prefs",
   tech:[["Ingest API → Kafka","absorb producer bursts; replayable"],["Per-channel workers → APNs/FCM/SES/Twilio","each provider has its own rate limits, retries, failure modes — isolate them"],["Prefs + device-token registry (DB)","check opt-outs BEFORE send; tokens go stale"],["Idempotency/dedup in Redis (event id, TTL)","producer retries must not double-notify"]],
   got:["Broadcast: don't enqueue 10M messages at the API — enqueue ONE event, expand in workers by user-shard","Collapse keys: 5 score updates → deliver only the latest","Provider feedback loops prune dead tokens (APNs tells you)","Per-user rate limit — being noisy is a product failure too"],
   arch:{nodes:[
     ["prod","Producer Services","cl",0,1,"Order shipped, friend request, marketing blast — anything that wants to notify."],
     ["gw","Notify API","svc",1,1,"Validates, assigns event id, publishes. A segment broadcast is ONE event here, not 10M."],
     ["kafka","Kafka","q",2,1,"Buffer + replay log; fan-out expansion happens downstream of it."],
     ["fan","Fan-out / Router","svc",3,1,"Expands segments into users (sharded), checks prefs + dedup, routes to channel topics with collapse keys."],
     ["prefs","Prefs + Tokens DB","db",3,0,"Opt-outs, quiet hours, channel choices, device tokens. Checked before send, always."],
     ["dedup","Dedup (Redis)","cache",3,2,"SET NX on (event id, user) with TTL — retries and replays can't double-send."],
     ["push","Push Workers","svc",4,0,"APNs/FCM with provider rate limits, backoff, and the token-feedback loop that prunes dead devices."],
     ["mail","Email/SMS Workers","svc",4,2,"SES/Twilio — slower, costlier channels with their own throttles and DLQs."]],
   edges:[
     ["prod","gw","POST /notify","Fire-and-forget from the producer's perspective."],
     ["gw","kafka","one event","Even for a broadcast — expansion is a worker concern."],
     ["kafka","fan","consume","Scales horizontally by partition."],
     ["fan","prefs","opt-out + tokens","No prefs check, no send. Ever."],
     ["fan","dedup","SET NX event+user","First writer wins; duplicates drop here."],
     ["fan","push","per-channel topic","Collapse key keeps only the latest of rapid-fire updates."],
     ["fan","mail","per-channel topic","Email/SMS get independent queues so a Twilio slowdown can't block push."]]}},

  {icon:"📈", name:"Robinhood / Stock Trading", scope:"live prices + order lifecycle", tags:["SSE","state-machine","reconcile","consistency"],
   fr:["Live prices for watched symbols","Place / cancel market & limit orders","Portfolio + order status"],
   nfr:["Orders: strongly consistent, never lost or duplicated","Prices: low-latency to millions (eventual is fine)","Full audit trail; exchange is an external async party"],
   oos:["The exchange's matching engine itself (we ROUTE to it)","Margin / options math","KYC / compliance workflows","Market-data licensing tiers"],
   api:"SSE /prices?symbols= · POST /orders (idem key) · DELETE /orders/:id · GET /portfolio",
   tech:[["Exchange feed → price service → per-symbol pub/sub → SSE","users subscribe to symbols; display path tolerates staleness"],["Order service + Postgres state machine","pending → routed → partially_filled → filled/cancelled; every transition persisted"],["Idempotent exchange gateway (client order ids, seq numbers)","timeout ≠ failure — the order may be live at the exchange"],["Fills → Kafka → portfolio projection","positions derived from the fill stream, event-sourced style"]],
   got:["Two paths, two consistency budgets: price display eventual, order path strict — say this framing out loud","Reconciliation with exchange records (drop-copy) resolves unknown states","Hot symbols (GME day) → shard pub/sub per symbol, fan out via SSE tiers","Cancel is also an order — races with fills; the state machine arbitrates"],
   arch:{nodes:[
     ["exch","Exchange","ext",0,0,"External matching engine: consumes orders, emits executions and market data. Async and occasionally ambiguous."],
     ["feed","Feed Handler","svc",1,0,"Normalizes the exchange market-data firehose into per-symbol price updates."],
     ["pubsub","Symbol Pub/Sub","q",2,0,"Topic per symbol; hot symbols shard further. Fan-out backbone for prices."],
     ["sse","SSE Servers","svc",3,0,"Hold client streams; each pushes only the symbols that client watches."],
     ["client","Client","cl",4,1,"Watches prices via SSE; places orders via REST with an idempotency key."],
     ["order","Order Service","svc",3,2,"Owns the order state machine; validates buying power; persists BEFORE routing."],
     ["odb","Orders DB (Postgres)","db",2,2,"Order rows with strict state transitions — the system of record for what the user asked."],
     ["gwx","Exchange Gateway","svc",1,2,"Sends orders with client-order-ids + sequence numbers; on timeout marks state UNKNOWN and lets reconciliation settle it."],
     ["fills","Fills Log (Kafka)","q",1,1,"Every execution appended; portfolio and history are projections of this stream."]],
   edges:[
     ["exch","feed","market data","Quotes and trades, firehose rate."],
     ["feed","pubsub","per-symbol updates","Publish to the symbol's topic."],
     ["pubsub","sse","subscribed symbols","Only what each connected client watches."],
     ["sse","client","SSE price stream","One-directional push — SSE over WebSocket is the right-sized tool."],
     ["client","order","POST /orders (idem key)","Duplicate submits collapse to one order."],
     ["order","odb","persist state machine","No transition happens only in memory."],
     ["order","gwx","route order","After it's durably 'pending'."],
     ["gwx","exch","submit (seq numbers)","Timeout here does NOT mean failure — never blind-retry a new order."],
     ["exch","gwx","acks + executions","Fills flow back asynchronously."],
     ["gwx","fills","append fills","The immutable record of what actually executed."],
     ["fills","order","update state","partially_filled → filled; cancel races resolved against real fills."]]}},

  {icon:"🎥", name:"FB Live Comments", scope:"realtime comments under live video", tags:["SSE","pub/sub","colocation","read-heavy"],
   fr:["Post a comment on a live stream","Viewers see new comments in near-realtime","Scroll back through history"],
   nfr:["Massive read fan-out: one comment → millions of viewers","Availability > consistency; ~few hundred ms nice-to-have","Bursty: celebrity streams dwarf the median"],
   oos:["Moderation / toxicity filtering","Reactions & badges","The video delivery itself (separate streaming system)","Ranked / highlighted comments"],
   api:"POST /videos/:id/comments · SSE /videos/:id/comments/stream · GET history?cursor",
   tech:[["SSE, not WebSocket","viewers overwhelmingly READ; comments post over plain HTTP — bidirectional plumbing is waste"],["Comment svc → DB (partition by videoId) → pub/sub → SSE servers","write path is boring; the fan-out is the problem"],["Colocate viewers of the same stream (consistent hashing videoId → SSE servers)","pub/sub delivers once per SERVER, not once per viewer"],["Batch/coalesce pushes (~200ms)","100 comments/s → 5 batched pushes/s per connection"]],
   got:["SSE vs WS decision with the read/write asymmetry argument — this is the signature trade-off","Per-server (not per-viewer) subscription is what makes celebrity streams survivable","Cursor pagination by (ts, commentId) for history","Graceful degradation: sample/drop comments client-side on extreme streams"],
   arch:{nodes:[
     ["poster","Commenter","cl",0,0,"Posts over plain HTTP POST — no persistent upstream channel needed."],
     ["csvc","Comment Service","svc",1,0,"Validates, persists, publishes to the video's topic. Stateless."],
     ["cdb","Comments DB","db",2,0,"Partitioned by liveVideoId, clustered by time — history reads are one-partition scans."],
     ["pubsub","Pub/Sub","q",2,1,"Topic per live video. Subscribers are SSE SERVERS, not viewers."],
     ["sse","SSE Servers","svc",3,1,"Each holds many viewer connections; viewers of the same video are packed onto few servers via consistent hashing on videoId."],
     ["viewer","Viewers","cl",4,1,"Millions of one-directional SSE streams; batched comment pushes every ~200ms."],
     ["ring","Hash Ring (videoId→server)","ext",3,0,"The colocation map: which SSE servers own which streams."]],
   edges:[
     ["poster","csvc","POST comment","Write path is tiny compared to the read fan-out."],
     ["csvc","cdb","persist","Durable first, broadcast second."],
     ["csvc","pubsub","publish to video topic","One publish per comment."],
     ["pubsub","sse","deliver per SERVER","A stream with 2M viewers on 20 servers = 20 deliveries, then local fan-out in memory."],
     ["sse","viewer","SSE (batched)","Coalesced pushes keep connection overhead sane."],
     ["ring","sse","placement","Consistent hashing keeps a stream's viewers together and rebalances on server churn."],
     ["viewer","cdb","history?cursor","Older comments via cursor pagination (through the API)."]]}},

  {icon:"🔨", name:"Online Auction (eBay)", scope:"live bidding, exactly-one winner", tags:["OCC","strong-consistency","SSE","scheduler"],
   fr:["Create auction (start price, end time)","Place bids; see current high bid live","Auction closes exactly once → winner"],
   nfr:["Bids: strongly consistent (no lost / late-accepted bids)","Bursty writes at closing seconds (sniping)","Read-heavy watching between bids"],
   oos:["Payments & escrow after the win","Search / browse / categories","Fraud & shill-bid detection","Proxy-bidding agents (mention, then scope)"],
   api:"POST /auctions · POST /auctions/:id/bids · SSE /auctions/:id",
   tech:[["Postgres with OCC or row lock on the auction's max_bid","accept iff amount > current AND status = open — one atomic decision point"],["Append-only bids table","full audit of every bid, accepted or rejected"],["Pub/sub → SSE for live price updates","watchers get updates pushed; cache serves reads between bids"],["Durable scheduler closes the auction (idempotent job)","reuses the job-scheduler design; close must survive crashes"]],
   got:["OCC (retry on conflict) vs pessimistic lock under sniping bursts — argue throughput vs contention","The status='open' check lives INSIDE the same transaction as the bid — that's what rejects late bids","Cache-based fast-reject (bid below current) is UX only; DB is truth","Anti-sniping extension (extend close on late bid) — good scope question to raise"],
   arch:{nodes:[
     ["client","Bidders / Watchers","cl",0,1,"Bid via POST; watch the current price over SSE."],
     ["gw","API Gateway","svc",1,1,"Routes bids, subscriptions, and auction CRUD."],
     ["bid","Bid Service","svc",2,1,"Fast-rejects obviously low bids from cache, then attempts the atomic accept in Postgres."],
     ["adb","Auctions + Bids (Postgres)","db",3,1,"Auction row holds current max; bids table is append-only audit. UPDATE ... WHERE amount > max AND status='open' is the whole guarantee."],
     ["cache","Current-price Cache","cache",3,0,"Serves watchers and the fast-reject path; refreshed on every accepted bid."],
     ["pubsub","Pub/Sub → SSE","q",2,0,"Accepted bids fan out to everyone watching the auction."],
     ["sched","Close Scheduler","svc",2,2,"A durable job per auction fires at end time: set status=closed, pick winner — idempotent, so retries are safe."],
     ["notif","Notifications","ext",3,2,"Winner + outbid alerts (the notification-service design)."]],
   edges:[
     ["client","gw","bid / watch","Two very different traffic shapes: bursty writes, steady reads."],
     ["gw","bid","POST bid","The consistency-critical path."],
     ["bid","cache","fast reject","Below current price? 409 without touching Postgres. Pure UX optimization."],
     ["bid","adb","atomic accept (OCC)","Compare-and-set against max_bid inside a transaction; conflict → retry with the fresh value."],
     ["adb","pubsub","accepted bid event","Truth changed — broadcast it."],
     ["pubsub","client","SSE price update","Watchers see the new high bid in ~ms."],
     ["sched","adb","close idempotently","status open→closed exactly once; late bids now fail the in-transaction status check."],
     ["sched","notif","winner / outbid","Post-close and during-auction alerts."]]}},

  {icon:"📮", name:"Distributed Message Queue", scope:"design Kafka-lite: topics, groups, replication", tags:["log","ISR","sharding","replication"],
   fr:["Producers publish to topics; consumers subscribe in groups","Ordering within a partition; ack + replay from offset"],
   nfr:["Durable once acked (survive broker loss)","High throughput (GB/s) — sequential IO","At-least-once baseline; exactly-once as an extension"],
   oos:["Stream processing on top (that's Flink)","Schema registry / serialization governance","Cross-region geo-replication (mention MirrorMaker-style)","Tiered / infinite storage"],
   api:"produce(topic, key, msg) · poll(group, topic) · commit(group, offsets)",
   tech:[["Partitioned append-only log on disk","sequential writes + page cache + zero-copy sendfile = disk at memory-ish speed"],["Leader + ISR replicas per partition","acks=all + min.insync.replicas: durability vs latency dial"],["Consumer groups with committed offsets","consumers own their position — replay = rewind; retention decouples producer from consumer"],["Raft/ZooKeeper for metadata + leader election","who leads each partition; epoch/fencing against zombie leaders"]],
   got:["WHY a log beats a B-tree 'queue table': no random IO, no delete churn, consumers are just offsets","Partition count = max parallelism per group — choosing it is a real commitment","Rebalancing pain: sticky assignment, cooperative rebalance","Pull (consumer-paced, natural backpressure) vs push — defend pull"],
   arch:{nodes:[
     ["prod","Producers","cl",0,1,"Publish records with a key; key → partition hash keeps related records ordered."],
     ["lead","Broker (leader, P0)","svc",1,1,"Owns partition 0: appends to its log, serves reads, tracks the in-sync replica set."],
     ["log","Append-only Log (disk)","db",2,0,"Segment files written sequentially; OS page cache + zero-copy make serving cheap. Retention by time/size, independent of consumption."],
     ["rep","Follower Replicas (ISR)","svc",2,2,"Fetch from the leader and append; acks=all means the leader confirms only after the ISR has the record."],
     ["meta","Metadata / Raft","ext",1,0,"Cluster membership, partition→leader mapping, leader election with epochs to fence zombies."],
     ["cons","Consumer Group","cl",3,1,"Partitions divided among group members; each consumer pulls at its own pace — built-in backpressure."],
     ["off","Offsets Store","db",3,0,"Committed (group, partition) → offset. Crash recovery = resume from last commit; replay = rewind it."]],
   edges:[
     ["prod","lead","produce (key→partition)","Same key, same partition, same order — the only ordering promise."],
     ["lead","log","sequential append","The core performance trick: never seek."],
     ["lead","rep","replicate","Followers pull and append; falling behind ejects them from the ISR."],
     ["rep","lead","ack (ISR)","With acks=all, the produce succeeds only once the ISR quorum has it — durable once acked."],
     ["meta","lead","leadership + epoch","Failover promotes an ISR member; the epoch fences the old leader's late writes."],
     ["cons","lead","pull from offset","Consumers read at their own speed; slow consumers hurt nobody until retention expires."],
     ["cons","off","commit offsets","At-least-once: commit AFTER processing; flipping the order gives at-most-once."]]}},

  {icon:"⚡", name:"Distributed Cache", scope:"design Redis-cluster-lite: shard, replicate, evict", tags:["consistent-hashing","LRU","hot-keys","replication"],
   fr:["get / put / delete with TTL","Scale horizontally by adding nodes","Survive a node failure without losing the cluster"],
   nfr:["Sub-ms latency, millions of QPS","Availability > consistency — it's a cache, misses are legal","Minimal key movement when the ring changes"],
   oos:["Durability / persistence guarantees (backing store's job)","Rich data structures (start with KV)","Multi-key transactions","AuthN/Z and encryption in transit"],
   api:"GET k · SET k v EX ttl · DEL k",
   tech:[["Consistent hashing + virtual nodes","adding a node moves ~1/N of keys, not all; vnodes smooth the distribution"],["Per-node LRU: hashmap + doubly-linked list","O(1) get/put/evict — the classic pairing, know it cold"],["Async replication to one replica per shard","fast failover; async because losing a few cache writes is fine"],["Client-side ring routing (or a thin proxy)","no central router bottleneck"]],
   got:["Hot key → replicate it to N nodes, client picks one at random (read spreading)","Thundering herd on expiry → TTL jitter + request coalescing (singleflight)","LRU vs LFU vs TinyLFU — one sentence on why LRU is the default","Ring change ≠ flush: only the moved ranges miss"],
   arch:{nodes:[
     ["app","App / Client Library","cl",0,1,"Embeds the ring: hashes the key, talks straight to the owning node. No hop through a coordinator."],
     ["ring","Hash Ring (config)","ext",1,0,"Cluster topology + vnode assignments; distributed to clients, updated on membership change."],
     ["n1","Cache Node A (primary)","cache",2,0,"Owns its key ranges: hashmap for O(1) lookup, doubly-linked list for O(1) LRU eviction, TTLs enforced lazily + by sweeper."],
     ["n2","Cache Node B (primary)","cache",2,1,"Another shard — same design, different ranges."],
     ["r1","Replica of A","cache",3,0,"Receives async replication; promoted on A's failure so the range doesn't go cold all at once."],
     ["gossip","Health / Gossip","svc",1,2,"Failure detection; drives ring updates and replica promotion."],
     ["db","Backing Store","db",3,2,"The real database behind the cache — misses fall through here (cache-aside from the app)."]],
   edges:[
     ["app","ring","key → node","Hash the key onto the ring locally; vnodes keep load even across heterogeneous boxes."],
     ["app","n1","GET / SET","Direct to the owner — one network hop."],
     ["app","n2","GET / SET","Different key range, different node."],
     ["n1","r1","async replicate","Fire-and-forget; a lost write costs one cache miss, not correctness."],
     ["gossip","ring","membership change","Node death or join reshapes the ring — only affected ranges move."],
     ["app","db","on miss (cache-aside)","Load from the source, SET with jittered TTL to avoid synchronized expiry stampedes."]]}},

  {icon:"🏠", name:"Airbnb / Hotel Booking", scope:"search by location+dates, book without overlap", tags:["geo","daterange","EXCLUDE","CDC"],
   fr:["Search listings by location, dates, guests","View listing + calendar","Book — two guests can NEVER hold overlapping dates"],
   nfr:["Strong consistency for booking; search can lag seconds","Read-heavy search; search < 500ms","Holds during checkout expire automatically"],
   oos:["Dynamic pricing engine","Reviews & ratings","Host↔guest messaging","Payments (assume processor) and ID verification"],
   api:"GET /search?lat&lng&in&out&guests · GET /listings/:id · POST /bookings (hold → confirm)",
   tech:[["Elasticsearch geo + denormalized availability","filter by location AND dates in one index; availability synced via CDC"],["Postgres EXCLUDE constraint (listing_id WITH =, daterange WITH &&)","the DB itself rejects overlapping bookings — the elegant core of the design"],["Alternative: one row per (listing, night) + UNIQUE","simpler mental model, insert all nights in one txn"],["Redis hold with TTL during checkout","soft reservation; expiry auto-releases"]],
   got:["Search availability is a HINT — re-verify inside the booking transaction; index lag must not cause double-booking","EXCLUDE USING gist is the star move — name it precisely","Hold-then-confirm mirrors Ticketmaster; TTL releases abandoned checkouts","Calendar updates → CDC → index; never dual-write"],
   arch:{nodes:[
     ["client","Guest","cl",0,1,"Searches with dates; books through a hold → confirm checkout."],
     ["gw","API Gateway","svc",1,1,"Splits the search read path from the booking write path."],
     ["search","Search Service","svc",2,0,"Geo + date-availability + guests query against the denormalized index."],
     ["es","ES (geo + availability)","db",3,0,"Listings with location and an availability calendar baked in — one query, no cross-system join. Seconds stale, and that's fine."],
     ["book","Booking Service","svc",2,2,"Places a TTL hold, then runs the confirming transaction that re-checks availability for real."],
     ["hold","Holds (Redis TTL)","cache",3,1,"Checkout-time soft lock per (listing, dates); vanishes on abandonment."],
     ["pg","Postgres (EXCLUDE)","db",3,2,"Bookings with a daterange column; EXCLUDE USING gist (listing_id WITH =, stay WITH &&) makes overlap physically uninsertable."],
     ["pay","Payment","ext",4,2,"Charge on confirm; failure releases the hold."]],
   edges:[
     ["client","gw","search / book","Two paths, two consistency budgets."],
     ["gw","search","GET /search","Location + dates + guests."],
     ["search","es","one-index query","Geo circle ∩ available dates ∩ capacity — all in the same document."],
     ["gw","book","POST /bookings","Start checkout."],
     ["book","hold","hold (TTL ~10min)","UX courtesy so the listing isn't sniped mid-payment."],
     ["book","pg","INSERT (constraint checks)","The truth: if the range overlaps an existing booking, the INSERT fails atomically — search staleness can't hurt you here."],
     ["book","pay","charge on confirm","Then the booking flips to confirmed."],
     ["pg","es","CDC availability sync","Confirmed bookings update the searchable calendar within seconds."]]}},

  {icon:"⌨️", name:"Typeahead / Autocomplete", scope:"top-k suggestions per keystroke", tags:["precompute","prefix","read-heavy","edge-cache"],
   fr:["Top-k suggestions for the current prefix","Ranked by query popularity","Rankings refresh from real query logs"],
   nfr:["p99 < 100ms — it must feel synchronous with typing","Extreme read volume: every keystroke of every user","Freshness in hours is fine (daily/hourly rebuild)"],
   oos:["Personalized suggestions","Spell correction / fuzzy matching","Multi-language tokenization details","Promoted / sponsored suggestions"],
   api:"GET /suggest?q=prefix → [top-k]",
   tech:[["Precompute top-k PER PREFIX offline; serving = one KV lookup","the trick: no trie walk, no ranking at request time"],["Sharded KV/Redis: prefix → [suggestions]","hash prefixes across shards; each lookup hits exactly one"],["Query logs → Kafka → aggregator → index builder","counts roll up offline; builder swaps in a fresh prefix table"],["Edge/CDN caching of hot prefixes","'a', 'the', 'ho' — a small set of prefixes is a huge share of traffic"]],
   got:["Say it plainly: a trie is the BUILD-TIME structure; serving is a hash lookup","Bound the table: prefixes up to ~7 chars, only k entries each — do the storage math","Client debounce (~50–100ms) + client-side prefix cache cut half the requests","Atomic index swap (build v2, flip pointer) — never update in place"],
   arch:{nodes:[
     ["client","Client","cl",0,1,"Debounces keystrokes, caches results for prefixes it already asked, extends locally while typing forward."],
     ["cdn","Edge Cache / CDN","ext",1,1,"Hot prefixes served without touching the origin at all."],
     ["sugg","Suggest Service","svc",2,1,"Normalizes the prefix (lowercase, trim), looks up one key, returns k strings."],
     ["kv","Prefix KV (sharded)","db",3,1,"prefix → precomputed top-k list. The entire serving cleverness is that there is none."],
     ["logs","Query Logs","cl",0,2,"Real searches stream in as the ranking signal."],
     ["kafka","Kafka","q",1,2,"Buffers the log firehose for aggregation."],
     ["agg","Aggregator","svc",2,2,"Counts queries per window (streaming or hourly batch)."],
     ["build","Index Builder","svc",3,2,"Walks counts trie-style to emit top-k per prefix; writes a fresh table and atomically swaps it in."]],
   edges:[
     ["client","cdn","GET /suggest?q=","Tiny cacheable GETs — perfect CDN food."],
     ["cdn","sugg","miss","Only cold prefixes reach the service."],
     ["sugg","kv","one key lookup","O(1) serving regardless of corpus size."],
     ["logs","kafka","query events","What people actually search drives what we suggest."],
     ["kafka","agg","consume","Windowed counts."],
     ["agg","build","counts","Rank per prefix, keep k."],
     ["build","kv","atomic swap","Version the table; flip the pointer; instant rollback if v2 is bad."]]}},

  {icon:"📉", name:"Metrics & Monitoring (Datadog-lite)", scope:"ingest metric firehose, query, alert", tags:["TSDB","write-heavy","downsampling","cardinality"],
   fr:["Ingest metrics from fleets of agents","Query/graph arbitrary series over time ranges","Threshold alerts, near-realtime"],
   nfr:["Write-heavy extreme: millions of points/s","Recent data hot & fast; years of history cheap","Alert evaluation latency in seconds"],
   oos:["Logs and traces (adjacent, separate systems)","Anomaly detection ML","On-call paging/rotation logic (PagerDuty's job)","Dashboard UI design"],
   api:"POST /ingest (batch) · GET /query?series&range&agg · POST /alerts {expr, threshold}",
   tech:[["Agents → gateway → Kafka","decouple the firehose from every consumer; replay on recovery"],["Stream pre-aggregation (10s bins) before storage","raw per-point writes would melt anything; bin first"],["TSDB: time-partitioned, per-series Gorilla compression","delta-of-delta timestamps + XOR values ≈ 1.4 bytes/point"],["Downsampling tiers: raw 15d → 1min 90d → 1h forever","old data shrinks; long-range queries read the coarse tier"]],
   got:["Cardinality is the killer — every unique tag combo is a new series; enforce limits and say why","Alert engine subscribes to the STREAM (seconds), not DB polling (minutes)","Hot recent data in memory, cold tiers in object storage, one query layer federating both","Late/out-of-order points: window grace + last-write-wins per bin"],
   arch:{nodes:[
     ["agents","Agents (fleet)","cl",0,1,"On every host/container: collect, batch, compress, ship every ~10s."],
     ["gw","Ingest Gateway","svc",1,1,"Auth, validation, cardinality enforcement — reject tag explosions at the door."],
     ["kafka","Kafka","q",2,1,"The firehose buffer; storage and alerting consume independently."],
     ["agg","Stream Aggregator","svc",3,0,"Pre-aggregates into 10s bins per series; handles late points within a grace window."],
     ["hot","Hot TSDB (memory/SSD)","db",4,0,"Recent, Gorilla-compressed, serving 99% of queries (dashboards look at NOW)."],
     ["cold","Cold Tier (S3)","db",4,1,"Downsampled rollups: 1-min then 1-hour resolution, kept ~forever for cheap."],
     ["alert","Alert Engine","svc",3,2,"Evaluates threshold expressions against the live stream — seconds of latency, no polling."],
     ["query","Query Service","svc",4,2,"Federates hot + cold transparently; picks resolution by time range."],
     ["notif","Notify","ext",3,1,"Fires into the notification system when a threshold trips."]],
   edges:[
     ["agents","gw","batched points","Compression + batching on the agent keeps network cost sane."],
     ["gw","kafka","validated stream","Cardinality limits enforced before anything is stored."],
     ["kafka","agg","consume","Binning turns millions of points/s into something storable."],
     ["agg","hot","10s bins","Compressed in-memory blocks, flushed to SSD."],
     ["hot","cold","downsample + age out","Raw expires at 15d; rollups live on."],
     ["kafka","alert","live stream","Alerting reads the same stream — independent failure domain from storage."],
     ["alert","notif","threshold trip","De-duplicated, flap-suppressed."],
     ["query","hot","recent ranges","Fast path for dashboards."],
     ["query","cold","long ranges","A year-long graph reads 1h rollups, not raw points."]]}},

  {icon:"🗺️", name:"Google Maps (Routing + ETA)", scope:"route A→B with live-traffic ETA", tags:["graph","precompute","CH","write-heavy"],
   fr:["Route A→B with accurate ETA","Traffic-aware: routes and ETAs reflect current conditions","Reroute mid-drive when a better route appears"],
   nfr:["Route compute < 1s on a continental graph","Location-ping ingest is write-heavy (millions of drivers)","ETA accuracy beats raw speed of computation"],
   oos:["Map tile rendering & serving","Places / POI search and geocoding details","Street View / satellite imagery","Offline maps"],
   api:"GET /route?from&to · POST /pings (location stream) · SSE reroute suggestions",
   tech:[["Road network = weighted graph, partitioned by region","nodes are intersections; edge weight = current travel time"],["Contraction Hierarchies precompute shortcuts","plain Dijkstra on a continent is seconds-to-minutes; CH answers in ms"],["Pings → Kafka → traffic aggregator → per-segment speeds","live weights from the driving fleet itself"],["ETA = live weights + historical time-of-day profiles","predicts the traffic you'll MEET, not just the traffic now"]],
   got:["The unlock is precomputation (CH/CCH) — plain Dijkstra is the naive-answer trap","Live traffic changes weights → customizable CH: topology precomputed, weights refreshed cheaply","Reroute = periodic cheap re-query from current position; push only if meaningfully better","Privacy: anonymize/aggregate pings; per-segment stats, not per-user trails"],
   arch:{nodes:[
     ["client","Navigating Client","cl",0,1,"Requests a route, streams location pings while driving, accepts pushed reroutes."],
     ["gw","API Gateway","svc",1,1,"Splits the read path (routing) from the write firehose (pings)."],
     ["route","Routing Service","svc",2,0,"Runs CH query: bidirectional search over the precomputed hierarchy with current weights; returns path + ETA."],
     ["graph","CH Graph Store","db",3,0,"Partitioned road graph + contraction shortcuts; topology rebuilt rarely, weights refreshed continuously."],
     ["kafka","Kafka (pings)","q",2,2,"Millions of location points/s from the fleet."],
     ["traffic","Traffic Aggregator","svc",3,2,"Map-matches pings to road segments, computes rolling per-segment speeds."],
     ["weights","Live Weights Store","cache",4,1,"Current travel time per segment; the bridge between ingest and routing."],
     ["hist","Historical Profiles","db",4,2,"Speed by segment × time-of-day × day-of-week — the predictive half of ETA."]],
   edges:[
     ["client","gw","route / pings","One request-response, one firehose."],
     ["gw","route","GET /route","A→B with departure time."],
     ["route","graph","CH query","Milliseconds instead of a continental Dijkstra."],
     ["route","weights","current segment costs","Live traffic enters the cost function."],
     ["route","hist","predictive costs","For the parts of the trip you'll reach in 40 minutes, use the 40-minutes-from-now profile."],
     ["gw","kafka","location pings","Write path never blocks the read path."],
     ["kafka","traffic","map-match + aggregate","Pings become anonymized per-segment speeds."],
     ["traffic","weights","refresh speeds","Continuously updated; no topology rebuild needed."],
     ["traffic","hist","roll into profiles","Today's traffic improves tomorrow's predictions."]]}},

  {icon:"🏆", name:"Gaming Leaderboard", scope:"realtime scores, top-N and my-rank", tags:["ZSET","sharding","write-heavy","TTL"],
   fr:["Submit / update score","Top-N; my rank + neighbors (±k)","Daily / weekly / all-time boards"],
   nfr:["Write-heavy: millions of players scoring constantly","Rank query < 100ms — even for the 40-millionth player","Near-realtime rank movement"],
   oos:["Cheat / anomaly detection","Matchmaking","Friends-only boards (same design, filtered set)","Rewards & payout distribution"],
   api:"POST /scores · GET /top?n · GET /rank/:playerId?around=k",
   tech:[["Redis sorted set per (board, window)","ZADD GT + ZREVRANK: O(log N) updates, O(log N + k) range reads — purpose-built"],["DB as durable source of truth, Redis as serving layer","rebuild any ZSET from the DB after a crash"],["Time-bucketed keys (board:2026-W28) with TTL","daily/weekly boards rotate themselves"],["At 100M+ players: shard ZSET by score band","rank = sum of higher bands' cardinalities + rank within own band"]],
   got:["Composite score packs tiebreak into the value: (score << 20) | (maxTs − ts) — earlier score wins ties","Do the memory math out loud: 100M members ≈ tens of GB → sharding isn't optional","my-rank-page = ZREVRANK then ZREVRANGE rank−k..rank+k","Approximate rank (band-level) is often acceptable — ask the interviewer"],
   arch:{nodes:[
     ["game","Game Clients","cl",0,1,"Report score events as matches finish."],
     ["gw","Score API","svc",1,1,"Validates (server-authoritative scores — never trust the client), routes to the board writer."],
     ["score","Score Service","svc",2,1,"Writes durable truth first, then updates the serving ZSETs for each active window."],
     ["db","Scores DB","db",3,2,"Every score event persisted — the rebuild source and audit trail."],
     ["zset","Redis ZSETs (sharded)","cache",3,0,"One sorted set per (board, window); score-band shards past ~100M members. TTL rotates expired windows away."],
     ["rank","Rank Query Service","svc",2,0,"Top-N via ZREVRANGE; my-rank via ZREVRANK (+neighbors); merges across band shards when sharded."],
     ["rebuild","Rebuilder","svc",4,1,"On Redis loss or shard change: replay from the DB into fresh ZSETs."]],
   edges:[
     ["game","gw","score events","Signed / server-verified — leaderboards attract cheaters."],
     ["gw","score","validated score","One path for all windows."],
     ["score","db","append event","Durability before serving."],
     ["score","zset","ZADD GT (per window)","Updates daily, weekly, all-time keys in one pipeline; GT keeps only improvements."],
     ["rank","zset","ZREVRANK / ZREVRANGE","Both top-N and my-rank are logarithmic — the whole reason ZSETs are the tool."],
     ["db","rebuild","replay","Cache is disposable; truth is not."],
     ["rebuild","zset","repopulate","Fresh sorted sets after failure or resharding."]]}},
];
